### ISSUE TITLE
Example for minio with ByteArrayConverter

### ISSUE THREAD

**Issue by Ihjaz** [apache/camel-kafka-connector-examples#312] opened 2021-03-29 10:04 UTC
Can you please add an exmaple for minio connector with ByteArrayConverter ?

I'm trying to move an image object from minio to kafka but it looks like the minio connector is consuming the object as 'STRING' and ByteArrayConecter is not able to process it.

**Comment by oscerd** [comment] 2021-03-29 10:09
What version are you using?

**Comment by oscerd** [comment] 2021-03-29 10:11
By the way the problem is in the camel component. We need to fix the behavior there. https://github.com/apache/camel/blob/master/components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioEndpoint.java#L163

**Comment by Ihjaz** [comment] 2021-03-29 11:05
> What version are you using?

camel-minio-kafka-connector-0.8.0

**Comment by oscerd** [comment] 2021-03-29 11:12
Needs a fix on the camel side.

**Comment by oscerd** [comment] 2021-03-29 12:09
Fixed on the Camel side: https://issues.apache.org/jira/browse/CAMEL-16423

This will be in 0.7.4 or 0.10.0

**Comment by Ihjaz** [comment] 2021-03-29 13:42
Thanks for the quick fix.

Can I test this fix if I build the camel-kafka-connector 0.7.4-snaphsot branch ?

**Comment by oscerd** [comment] 2021-03-29 14:00
Not out of the box. You'll need to point to the snapshot and you'll need to build camel 3.7.4 snapshot too, to be sure it is aligned

**Comment by Ihjaz** [comment] 2021-03-29 15:26
Camel-minio compilation failed. It seems like you have imported `org.testcontainers.shaded.org.apache.commons.io.IOUtils` instead of `org.apache.commons.compress.utils.IOUtils`.

**Comment by oscerd** [comment] 2021-03-29 15:30
Fixed.

**Comment by oscerd** [comment] 2021-03-30 21:07
Did you try it?

**Comment by Ihjaz** [comment] 2021-03-31 06:31
I will be testing it today.

**Comment by Ihjaz** [comment] 2021-03-31 10:24
I've tried it. I was able to successfully consume an image, audio and video file with `org.apache.kafka.connect.converters.ByteArrayConverter`.

Thanks again for the quick fix.

**Comment by oscerd** [comment] 2021-03-31 10:26
Super happy to help!

**Closed** 2021-03-31 10:49 UTC
